"""make timestamps timezone aware

Revision ID: a5e726fabfbd
Revises: fef7a7f04a1d
Create Date: 2026-02-21 21:36:00.378766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5e726fabfbd'
down_revision: Union[str, None] = 'fef7a7f04a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.alter_column('client', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="updated_at AT TIME ZONE 'UTC'")
    op.alter_column('client_advisor', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.alter_column('client_note', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.alter_column('client_note', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="updated_at AT TIME ZONE 'UTC'")
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="created_at AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.alter_column('client_note', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="updated_at AT TIME ZONE 'UTC'")
    op.alter_column('client_note', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.alter_column('client_advisor', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.alter_column('client', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="updated_at AT TIME ZONE 'UTC'")
    op.alter_column('client', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="created_at AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###
