"""add client advisor table

Revision ID: e31f621cbcfc
Revises: 920ec93bbdae
Create Date: 2026-02-21 16:55:12.988556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31f621cbcfc'
down_revision: Union[str, None] = '920ec93bbdae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_advisor',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'user_id'),
    sa.UniqueConstraint('client_id', 'user_id')
    )

    client_table = sa.table(
        'client',
        sa.column('id', sa.String()),
        sa.column('assigned_user_id', sa.String()),
    )
    client_advisor_table = sa.table(
        'client_advisor',
        sa.column('client_id', sa.String()),
        sa.column('user_id', sa.String()),
        sa.column('created_at', sa.DateTime()),
    )
    op.execute(
        sa.insert(client_advisor_table).from_select(
            ['client_id', 'user_id', 'created_at'],
            sa.select(
                client_table.c.id,
                client_table.c.assigned_user_id,
                sa.func.now(),
            ).where(client_table.c.assigned_user_id.is_not(None))
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_advisor')
    # ### end Alembic commands ###
