"""add client note table

Revision ID: fef7a7f04a1d
Revises: e31f621cbcfc
Create Date: 2026-02-21 19:14:04.639000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef7a7f04a1d'
down_revision: Union[str, None] = 'e31f621cbcfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_note',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('author_user_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_note_author_user_id'), 'client_note', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_client_note_client_id'), 'client_note', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_note_client_id'), table_name='client_note')
    op.drop_index(op.f('ix_client_note_author_user_id'), table_name='client_note')
    op.drop_table('client_note')
    # ### end Alembic commands ###
